$ANSIBLE_VAULT;1.1;AES256
35633833613765646133356339353761653937373134616131623466333633623666393338393263
6534373261396562313466353262636464333365376664370a373538343330356334303764653530
38313032323335343434646164393633623938353934666534666637306139626338653236333334
3032373734633665650a393166336334396434326333633336633136313464636639343361666462
65333339396562323431643931633335333039623866313630353064363734333033
