$ANSIBLE_VAULT;1.1;AES256
63633430343234373838636138386366613064323663666235306363356637373333643937623361
3833663834353635306464306465633262613533633062610a646335646564643631653534646165
38616539663965633266633262356462663437353636366363373339323235643737356466623732
3537613563383462310a323466373763323131383434303130366532366332643133323838363737
39313132363666343464633966313037343236646434373165366564386162393135
