$ANSIBLE_VAULT;1.1;AES256
31313264613861623566303463653761353039616133303263663665623735316231363161653565
3261333966616661376136663834653765386436373464650a343061386565643231623539333833
35343061633238633335363833356236363737343065643662343065336330363931316631353262
6336623634393965310a393830373763646262393561366266656432653264356439346230656433
62616466633738323636613635353862306465663034303834363238373636333434363465336665
62633834353461666332663637663139356533643835343537376361373835333039373163313732
376461636334633362386464656438333335
